CREATE TABLE "system" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "datetime" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "nopenings" INTEGER NOT NULL DEFAULT 0,
  "nerrors" INTEGER NOT NULL DEFAULT 0,
  "nattempts" INTEGER NOT NULL DEFAULT 0,
  "lastattempt" TIMESTAMP,
  "lockeduntil" TIMESTAMP
);
